version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - dependency
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: bindgen
    versions:
    - 0.57.0
    - 0.58.0
  - dependency-name: pretty_assertions
    versions:
    - 0.7.1
